spring:
  application:
    name: ms-user

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_usuarios}
    username: ${DB_USER:cordytech}
    password: ${DB_PASS:cordytech123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # crea/actualiza tablas automáticamente
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:cordytech-secret-2025}

management:
  endpoints:
    web:
      exposure:
        include: health
